services:
  - type: web
    name: sandbook
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: ML_CLIENT_ID
        sync: false
      - key: ML_CLIENT_SECRET
        sync: false
